#include "JSONDescription.h"

const char TemplateJSON[] = "[{\n"
"	'param' : 'Utm',\n"
"	'type' : 'measure',\n"
"	'ranges': [\n"
"		{\n"
"			'rangeId' : '1',\n"
"			'unitsMultiply' : '1'\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '2',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		}]\n"
"},\n"
"{\n"
"	'param' : 'Itm',\n"
"	'type' : 'set',\n"
"	'ranges': [\n"
"		{\n"
"			'rangeId' : '3',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		}]\n"
"},\n"
"{\n"
"	'param' : 'Itm',\n"
"	'type' : 'measure',\n"
"	'ranges': [\n"
"		{\n"
"			'rangeId' : '4',\n"
"			'unitsMultiply' : '1'\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '5',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		}]\n"
"}]";

float Utm1Min, Utm1Max, Utm2Min, Utm2Max, ItmSetMin, ItmSetMax, ItmMeas1Min, ItmMeas1Max, ItmMeas2Min, ItmMeas2Max;
